sudo: required

services:
  - docker

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

script:
  - cp -nrv post/. .
  - cp -nrv theme/. .
  - sed -i 's/jekyll-admin//' _config.yml
  - sed -i 's/gem .jekyll-admin.//' Gemfile
  - bundle install
  - sed -i 's/jekyll-theme-csdn/blog-csdn/' _config.yml
  - sed -i 's/moyummy/moyummy/' _config.yml
  - cat _config.yml
  - bundle exec jekyll build
  - ls docs

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then echo "commit on master"; fi